
import { DrawType, PointName } from "@/components/canvas/enum";
import { Step } from "./type";

export const steps: Step[] = [
	{
		title: "Define 1 cm",
		description: "Set two points, 1 cm apart",
		pointName: PointName.Distance,
		type: DrawType.SetPxDistance,
		isCompleted: false,
	},
	{
		title: "S",
		description: "Set point of S",
		pointName: PointName.S,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "N",
		description: "Set point of N",
		pointName: PointName.N,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "Pr",
		description: "Set point of Pr",
		pointName: PointName.Pr,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "Or",
		description: "Set point of Or",
		pointName: PointName.Or,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "PNS",
		description: "Set point of PNS",
		pointName: PointName.PNS,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "ANS",
		description: "Set point of ANS",
		pointName: PointName.ANS,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "A",
		description: "Set point of A",
		pointName: PointName.A,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "A1",
		description: "Set point of A1",
		pointName: PointName.A1,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "Ar",
		description: "Set point of Ar",
		pointName: PointName.Ar,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "B1",
		description: "Set point of B1",
		pointName: PointName.B1,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "Br",
		description: "Set point of Br",
		pointName: PointName.Br,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "Mp",
		description: "Set point of Mp",
		pointName: PointName.Mp,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "pMp",
		description: "Set point of pMp",
		pointName: PointName.pMp,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "B",
		description: "Set point of B",
		pointName: PointName.B,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "Po",
		description: "Set point of Po",
		pointName: PointName.Po,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "Me to Lr",
		description: "Set point of Me to Lr",
		pointName: PointName.MeToLr,
		type: DrawType.Line,
		isCompleted: false,
	},
	{
		title: "Ramus plane",
		description: "Set start line from Go",
		pointName: PointName.RamusPlane,
		type: DrawType.Line,
		isCompleted: false,
	},
	{
		title: "Ba",
		description: "Set point of Ba",
		pointName: PointName.Ba,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "EN",
		description: "Set point of EN",
		pointName: PointName.EN,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "UL",
		description: "Set point of UL",
		pointName: PointName.UL,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "LL",
		description: "Set point of LL",
		pointName: PointName.LL,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "Dt",
		description: "Set point of Dt",
		pointName: PointName.Dt,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "D",
		description: "Set point of D",
		pointName: PointName.D,
		type: DrawType.Dot,
		isCompleted: false,
	},
	{
		title: "PoC",
		description: "Set point of PoC",
		pointName: PointName.PoC,
		type: DrawType.Line,
		isCompleted: false,
	},
];
